# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev2+gdf5ae5f.d20230827'
__version_tuple__ = version_tuple = (0, 1, 'dev2', 'gdf5ae5f.d20230827')
