# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev37+gd0b3187.d20230919'
__version_tuple__ = version_tuple = (0, 1, 'dev37', 'gd0b3187.d20230919')
